language: node_js
node_js: 14

addons:
  apt:
    packages:
      - libgconf-2-4 # Required by cypress
cache:
  yarn: true
  directories:
    - ~/.cache # Required by cypress

script:
- yarn build
- yarn test

deploy:

- provider: npm
  email: tylergrinn@gmail.com
  skip_cleanup: true
  api_key:
    secure: osMW6xEQn2v4jP61I6kphIuBjSVxTLgor2nDEzFmNy3Cn2Vaav6sv2rkyqPZTntXupmCAOdf9ExC14pf5z+IAPcx+j6bKC17LhRNFAjzk1uxY76QMnGcd0kboJVQfUHVouaZskzFjU7ccGTQjxUhQGcAD4/2W8ugDmjpOcYrWrxZZ0SyVr7TZrdi4hvi+e/ZUfJmuKkeimEjdqiHujxMuM1Lo4x5rbgCNH8j/fKoorp9lSh8UIOJwC3M4tYHt5lAcSEQGAYE3SlM09hCicqZi+2APiiNn0oxYMeZtM40cmtXgRQPU/lbapvFVmGTtZGN7Xjxea6/hC1rpNIV0ayGERZOng6qSdAxrrAst1Du+91m/tqASYCBDBLnD6fmGnkFdNlF0OAZKJlzZHKK5i62EnsGPmxtnsj49Eq3rd+f/RH6VV5wtGTRvxzRF+Uv6NmhKGses8ijom1BalINISpNTMoKWnIZ61jB4uGQVky7j7Rz22X+u4Voy6awglvlQdggvUGFZhmDIgtpa4EQbjjZBJRT/m1kbV+I/29bpW5ETUdxn49g6w3RX8uzCpZyhpMshcvT8QMCoFwH5aouAuEscMfBRu41S6tly0dfUgXlPFPxPJeubenShGwSGmGbMrs+tnnHt4QZPGaooCIDWLwo1EOEpn7uHDv68Tj8yvDuBRU=
  on:
    tags: true
    repo: tylergrinn/vue-time-picker
  skip_cleanup: true

- provider: surge
  project: dist
  domain: vue-time-picker.surge.sh
  on:
    tags: true
    repo: tylergrinn/vue-time-picker
  skip_cleanup: true
